### ISSUE TITLE
Please provide some sort of guide on self hosting?

### ISSUE THREAD

**Issue by ghost** [TempleWeb/HolyJS#1]
I can't figure out how to self host this. I built it with the makefile, but now I'm confused as to running it? I tried running the html file with firefox but the input is blank, and the examples does nothing, etc.

**Comment by leozamboni** [comment]
Hello, thank you for opening an issue.

For local run you need a HTTP server, you can do this with python3:
```
python3 -m http.server 8000   
```
or with bun:
```
bun dev
```
Now you will need only the "holy.js" file. 

Make sure you have a input tag with "stdin" id and other with "stdout/stderr" in your HTML DOM:

```
 <textarea id="stdin"></textarea>   
 <textarea id="stdout/stderr"></textarea>
```

The "stdin" will be for the HolyC code and the "stdout/stderr" the output of the interpreter.

After you will need to import this procedure in your BOM inside the head tag:
```
<script defer type="module">
     import { holyc_web_run } from "./holy.js"
     window.holyc_web_run = holyc_web_run;
 </script>  
```
You can call this procedure for run the stdin with a button, for example:

```
<button onclick="holyc_web_run()">RUN(▶)</button>
```

When you click, the interperter will get the code in the "stdin" tag and put the output inside the tag with "stdout/stderr" id.

**Comment by ghost** [comment]
Lifesaver. Tysm.
